#############################################################################
# Makefile for building: HelpOptions.app/Contents/MacOS/HelpOptions
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  ../MainProgram/HelpOptions copy.pro
# Template: app
# Command: /Users/AustinVaday/QT/5.3/ios/bin/qmake -spec macx-ios-clang CONFIG+=x86 CONFIG+=iphonesimulator -spec macx-xcode -o HelpOptions.xcodeproj/project.pbxproj ../MainProgram/HelpOptions\ copy.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/AustinVaday/QT/5.3/ios/bin/qmake
HelpOptions.xcodeproj/project.pbxproj: ../MainProgram/HelpOptions\ copy.pro ../../../QT/5.3/ios/mkspecs/macx-ios-clang/qmake.conf ../../../QT/5.3/ios/mkspecs/features/spec_pre.prf \
		../../../QT/5.3/ios/mkspecs/qdevice.pri \
		../../../QT/5.3/ios/mkspecs/features/device_config.prf \
		../../../QT/5.3/ios/mkspecs/common/shell-unix.conf \
		../../../QT/5.3/ios/mkspecs/common/unix.conf \
		../../../QT/5.3/ios/mkspecs/common/mac.conf \
		../../../QT/5.3/ios/mkspecs/common/ios.conf \
		../../../QT/5.3/ios/mkspecs/common/gcc-base.conf \
		../../../QT/5.3/ios/mkspecs/common/gcc-base-mac.conf \
		../../../QT/5.3/ios/mkspecs/common/clang.conf \
		../../../QT/5.3/ios/mkspecs/common/clang-mac.conf \
		../../../QT/5.3/ios/mkspecs/common/ios/clang.conf \
		../../../QT/5.3/ios/mkspecs/common/ios/qmake.conf \
		../../../QT/5.3/ios/mkspecs/qconfig.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_core.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_declarative.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_enginio.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_gui.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_help.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_network.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_qml.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_quick.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_script.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_sql.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_svg.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_xml.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qdds.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qjp2.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmng.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../../QT/5.3/ios/mkspecs/features/qt_functions.prf \
		../../../QT/5.3/ios/mkspecs/features/qt_config.prf \
		../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/qt_config.prf \
		../../../QT/5.3/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../../QT/5.3/ios/mkspecs/macx-xcode/qmake.conf \
		../../../QT/5.3/ios/mkspecs/features/spec_post.prf \
		../../../QT/5.3/ios/mkspecs/features/exclusive_builds.prf \
		../../../QT/5.3/ios/mkspecs/features/default_pre.prf \
		../../../QT/5.3/ios/mkspecs/features/mac/default_pre.prf \
		../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/default_pre.prf \
		../../../QT/5.3/ios/mkspecs/features/resolve_config.prf \
		../../../QT/5.3/ios/mkspecs/features/default_post.prf \
		../../../QT/5.3/ios/mkspecs/features/mac/sdk.prf \
		../../../QT/5.3/ios/mkspecs/features/mac/default_post.prf \
		../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../../QT/5.3/ios/mkspecs/features/c++11.prf \
		../../../QT/5.3/ios/mkspecs/features/mac/objective_c.prf \
		../../../QT/5.3/ios/mkspecs/features/warn_on.prf \
		../../../QT/5.3/ios/plugins/platforms/libqios_iphonesimulator_debug.prl \
		../../../QT/5.3/ios/mkspecs/features/qt.prf \
		../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/qt.prf \
		../../../QT/5.3/ios/mkspecs/features/resources.prf \
		../../../QT/5.3/ios/mkspecs/features/moc.prf \
		../../../QT/5.3/ios/mkspecs/features/unix/opengl.prf \
		../../../QT/5.3/ios/mkspecs/features/uic.prf \
		../../../QT/5.3/ios/mkspecs/features/unix/thread.prf \
		../../../QT/5.3/ios/mkspecs/features/mac/rez.prf \
		../../../QT/5.3/ios/mkspecs/features/testcase_targets.prf \
		../../../QT/5.3/ios/mkspecs/features/exceptions.prf \
		../../../QT/5.3/ios/mkspecs/features/yacc.prf \
		../../../QT/5.3/ios/mkspecs/features/lex.prf \
		../MainProgram/HelpOptions\ copy.pro \
		../../../QT/5.3/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Users/AustinVaday/QT/5.3/ios/plugins/platforms/libqios_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/lib/libQt5PlatformSupport_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/lib/libQt5Gui_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/lib/libQt5Core_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/lib/libqtharfbuzzng_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/lib/libQt5Widgets_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/accessible/libqtaccessiblewidgets_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqdds_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqicns_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqico_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqjp2_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqmng_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqtga_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqtiff_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqwbmp_iphonesimulator_debug.prl \
		/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqwebp_iphonesimulator_debug.prl
	$(QMAKE) -spec macx-ios-clang CONFIG+=x86 CONFIG+=iphonesimulator -spec macx-xcode -o HelpOptions.xcodeproj/project.pbxproj ../MainProgram/HelpOptions\ copy.pro
../../../QT/5.3/ios/mkspecs/features/spec_pre.prf:
../../../QT/5.3/ios/mkspecs/qdevice.pri:
../../../QT/5.3/ios/mkspecs/features/device_config.prf:
../../../QT/5.3/ios/mkspecs/common/shell-unix.conf:
../../../QT/5.3/ios/mkspecs/common/unix.conf:
../../../QT/5.3/ios/mkspecs/common/mac.conf:
../../../QT/5.3/ios/mkspecs/common/ios.conf:
../../../QT/5.3/ios/mkspecs/common/gcc-base.conf:
../../../QT/5.3/ios/mkspecs/common/gcc-base-mac.conf:
../../../QT/5.3/ios/mkspecs/common/clang.conf:
../../../QT/5.3/ios/mkspecs/common/clang-mac.conf:
../../../QT/5.3/ios/mkspecs/common/ios/clang.conf:
../../../QT/5.3/ios/mkspecs/common/ios/qmake.conf:
../../../QT/5.3/ios/mkspecs/qconfig.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_clucene_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_core.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_core_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_declarative.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_declarative_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_enginio.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_enginio_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_gui.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_help.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_help_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_network.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_network_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_opengl.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_positioning.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_printsupport.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_qml.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_quick.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_script.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_script_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_scripttools.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_sensors.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_sql.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_svg.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_testlib.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_uitools.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_websockets.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_widgets.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_xml.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qdds.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qicns.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qico.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qios.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qjp2.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qmng.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtaccessiblequick.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtga.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../QT/5.3/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../../../QT/5.3/ios/mkspecs/features/qt_functions.prf:
../../../QT/5.3/ios/mkspecs/features/qt_config.prf:
../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/qt_config.prf:
../../../QT/5.3/ios/mkspecs/macx-ios-clang/qmake.conf:
../../../QT/5.3/ios/mkspecs/macx-xcode/qmake.conf:
../../../QT/5.3/ios/mkspecs/features/spec_post.prf:
../../../QT/5.3/ios/mkspecs/features/exclusive_builds.prf:
../../../QT/5.3/ios/mkspecs/features/default_pre.prf:
../../../QT/5.3/ios/mkspecs/features/mac/default_pre.prf:
../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/default_pre.prf:
../../../QT/5.3/ios/mkspecs/features/resolve_config.prf:
../../../QT/5.3/ios/mkspecs/features/default_post.prf:
../../../QT/5.3/ios/mkspecs/features/mac/sdk.prf:
../../../QT/5.3/ios/mkspecs/features/mac/default_post.prf:
../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../../QT/5.3/ios/mkspecs/features/c++11.prf:
../../../QT/5.3/ios/mkspecs/features/mac/objective_c.prf:
../../../QT/5.3/ios/mkspecs/features/warn_on.prf:
../../../QT/5.3/ios/plugins/platforms/libqios_iphonesimulator_debug.prl:
../../../QT/5.3/ios/mkspecs/features/qt.prf:
../../../QT/5.3/ios/mkspecs/macx-ios-clang/features/qt.prf:
../../../QT/5.3/ios/mkspecs/features/resources.prf:
../../../QT/5.3/ios/mkspecs/features/moc.prf:
../../../QT/5.3/ios/mkspecs/features/unix/opengl.prf:
../../../QT/5.3/ios/mkspecs/features/uic.prf:
../../../QT/5.3/ios/mkspecs/features/unix/thread.prf:
../../../QT/5.3/ios/mkspecs/features/mac/rez.prf:
../../../QT/5.3/ios/mkspecs/features/testcase_targets.prf:
../../../QT/5.3/ios/mkspecs/features/exceptions.prf:
../../../QT/5.3/ios/mkspecs/features/yacc.prf:
../../../QT/5.3/ios/mkspecs/features/lex.prf:
../MainProgram/HelpOptions copy.pro:
../../../QT/5.3/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Users/AustinVaday/QT/5.3/ios/plugins/platforms/libqios_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/lib/libQt5PlatformSupport_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/lib/libQt5Gui_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/lib/libQt5Core_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/lib/libqtharfbuzzng_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/lib/libQt5Widgets_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/accessible/libqtaccessiblewidgets_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqdds_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqicns_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqico_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqjp2_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqmng_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqtga_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqtiff_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqwbmp_iphonesimulator_debug.prl:
/Users/AustinVaday/QT/5.3/ios/plugins/imageformats/libqwebp_iphonesimulator_debug.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-ios-clang CONFIG+=x86 CONFIG+=iphonesimulator -spec macx-xcode -o HelpOptions.xcodeproj/project.pbxproj ../MainProgram/HelpOptions\ copy.pro

qmake_all: FORCE

